# Generated by Django 4.2.2 on 2023-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_product_productpair_user_delete_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=250000),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=250000),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(max_length=2000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250000),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutri_score',
            field=models.CharField(max_length=2000000),
        ),
    ]
